import json

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}

cells = [
    md([
        "# Análise de Despesas das Capitais Brasileiras (2020–2025)\n",
        "\n",
        "**Fonte:** FINBRA/Siconfi — Despesas por Função (Anexo I-E)  \n",
        "**Período:** 2020–2024 (2025 com apenas 11 capitais declaradas — excluído de comparações)  \n",
        "**Indicador central:** Taxa de Execução = (Despesas Pagas ÷ Despesas Empenhadas) × 100  \n",
        "\n",
        "Escolhi DuckDB como motor de consulta por permitir rodar SQL analítico diretamente sobre o\n",
        "Parquet sem carregar tudo na memória — ideal para dados que tendem a crescer a cada ano."
    ]),

    code([
        "import duckdb\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from pathlib import Path\n",
        "\n",
        "Path('saidas').mkdir(exist_ok=True)\n",
        "sns.set_theme(style='whitegrid')\n",
        "con = duckdb.connect('finbra.duckdb')"
    ]),

    md(["## 1. Completude dos dados por ano\n",
        "\n",
        "Antes de qualquer análise, é preciso saber quantas capitais declararam dados em cada ano.\n",
        "Comparar 2024 (26 capitais) com 2025 (11 capitais) em valores absolutos levaria a conclusões erradas."
    ]),

    code([
        "completude = con.execute(\"\"\"\n",
        "    SELECT\n",
        "        ano,\n",
        "        COUNT(DISTINCT \\\"Cod.IBGE\\\") AS capitais,\n",
        "        ROUND(COUNT(DISTINCT \\\"Cod.IBGE\\\") * 100.0 / 26, 0) AS pct_completo\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "    GROUP BY ano\n",
        "    ORDER BY ano\n",
        "\"\"\").df()\n",
        "\n",
        "print(completude.to_string(index=False))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "cores = ['#e74c3c' if c < 26 else '#2ecc71' for c in completude['capitais']]\n",
        "ax.bar(completude['ano'].astype(str), completude['capitais'], color=cores)\n",
        "ax.axhline(26, color='gray', linestyle='--', linewidth=0.8)\n",
        "ax.set_ylim(0, 30)\n",
        "ax.set_xlabel('Ano')\n",
        "ax.set_ylabel('Número de capitais')\n",
        "ax.set_title('Capitais com dados declarados por ano')\n",
        "for i, (ano, cap) in enumerate(zip(completude['ano'], completude['capitais'])):\n",
        "    ax.text(i, cap + 0.3, str(cap), ha='center', fontsize=10)\n",
        "plt.tight_layout()\n",
        "plt.savefig('saidas/completude.png', dpi=150)\n",
        "plt.show()"
    ]),

    md(["## 2. Taxa de Execução por Capital (2020–2024)\n",
        "\n",
        "Quanto do que cada capital **empenhou** efetivamente **saiu do caixa** no período?\n",
        "Uma taxa baixa indica acúmulo de restos a pagar — compromissos que ficam para o ano seguinte."
    ]),

    code([
        "taxa_geral = con.execute(\"\"\"\n",
        "    SELECT\n",
        "        UF,\n",
        "        ROUND(\n",
        "            100.0 * SUM(CASE WHEN Coluna = 'Despesas Pagas' THEN Valor ELSE 0 END) /\n",
        "            NULLIF(SUM(CASE WHEN Coluna = 'Despesas Empenhadas' THEN Valor ELSE 0 END), 0),\n",
        "        1) AS taxa_execucao\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "      AND ano BETWEEN 2020 AND 2024\n",
        "      AND Coluna IN ('Despesas Empenhadas', 'Despesas Pagas')\n",
        "    GROUP BY UF\n",
        "    ORDER BY taxa_execucao DESC\n",
        "\"\"\").df()\n",
        "\n",
        "taxa_geral['rank'] = range(1, len(taxa_geral) + 1)\n",
        "maceio_taxa = taxa_geral.loc[taxa_geral['UF'] == 'AL', 'taxa_execucao'].values[0]\n",
        "maceio_rank = taxa_geral.loc[taxa_geral['UF'] == 'AL', 'rank'].values[0]\n",
        "print(f'Maceió (AL): {maceio_taxa}% — {maceio_rank}º lugar entre 26 capitais')\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 10))\n",
        "cores = ['#e74c3c' if uf == 'AL' else '#3498db' for uf in taxa_geral['UF']]\n",
        "ax.barh(taxa_geral['UF'][::-1], taxa_geral['taxa_execucao'][::-1], color=cores[::-1])\n",
        "ax.axvline(taxa_geral['taxa_execucao'].mean(), color='gray', linestyle='--', linewidth=1,\n",
        "           label=f'Média: {taxa_geral[\"taxa_execucao\"].mean():.1f}%')\n",
        "ax.set_xlabel('Taxa de Execução (%)')\n",
        "ax.set_title('Taxa de Execução por Capital (2020–2024)\\nVermelho = Maceió')\n",
        "ax.legend()\n",
        "ax.set_xlim(70, 105)\n",
        "plt.tight_layout()\n",
        "plt.savefig('saidas/taxa_execucao_geral.png', dpi=150)\n",
        "plt.show()"
    ]),

    md(["## 3. Taxa de Execução por Função (Top 8)\n",
        "\n",
        "O comportamento muda bastante dependendo da área de atuação. Algumas funções têm execução\n",
        "quase total; outras acumulam sistematicamente restos a pagar."
    ]),

    code([
        "top_funcoes = con.execute(\"\"\"\n",
        "    SELECT Conta\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao' AND ano BETWEEN 2020 AND 2024\n",
        "      AND Coluna = 'Despesas Pagas'\n",
        "    GROUP BY Conta\n",
        "    ORDER BY SUM(Valor) DESC\n",
        "    LIMIT 8\n",
        "\"\"\").df()['Conta'].tolist()\n",
        "\n",
        "placeholders = ', '.join([f\"'{c}'\" for c in top_funcoes])\n",
        "\n",
        "heatmap_df = con.execute(f\"\"\"\n",
        "    SELECT\n",
        "        UF,\n",
        "        SPLIT_PART(Conta, ' - ', 2) AS funcao,\n",
        "        ROUND(\n",
        "            100.0 * SUM(CASE WHEN Coluna = 'Despesas Pagas' THEN Valor ELSE 0 END) /\n",
        "            NULLIF(SUM(CASE WHEN Coluna = 'Despesas Empenhadas' THEN Valor ELSE 0 END), 0),\n",
        "        1) AS taxa\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "      AND ano BETWEEN 2020 AND 2024\n",
        "      AND Coluna IN ('Despesas Empenhadas', 'Despesas Pagas')\n",
        "      AND Conta IN ({placeholders})\n",
        "    GROUP BY UF, Conta\n",
        "\"\"\").df()\n",
        "\n",
        "pivot = heatmap_df.pivot(index='UF', columns='funcao', values='taxa')\n",
        "ordem_uf = taxa_geral.set_index('UF')['taxa_execucao'].reindex(pivot.index).sort_values(ascending=False).index\n",
        "pivot = pivot.loc[ordem_uf]\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(13, 9))\n",
        "sns.heatmap(pivot, annot=True, fmt='.0f', cmap='RdYlGn', vmin=60, vmax=100,\n",
        "            linewidths=0.3, ax=ax, cbar_kws={'label': 'Taxa de Execução (%)'})\n",
        "ax.set_title('Taxa de Execução por Função e Capital (2020–2024)', fontsize=13)\n",
        "ax.set_xlabel('')\n",
        "ax.set_ylabel('Capital (UF)')\n",
        "ax.tick_params(axis='x', rotation=30)\n",
        "plt.tight_layout()\n",
        "plt.savefig('saidas/heatmap_taxa_funcao.png', dpi=150)\n",
        "plt.show()"
    ]),

    md(["## 4. Saúde e Educação — Gasto Per Capita (2024)\n",
        "\n",
        "Comparar valores absolutos é injusto: São Paulo tem população 20× maior que Boa Vista.\n",
        "O gasto **por habitante** nivela o campo e revela quem de fato investe mais."
    ]),

    code([
        "per_capita = con.execute(\"\"\"\n",
        "    SELECT\n",
        "        UF,\n",
        "        ROUND(SUM(CASE WHEN Conta LIKE '10 - %' THEN Valor ELSE 0 END) / MAX(\\\"População\\\"), 0) AS saude,\n",
        "        ROUND(SUM(CASE WHEN Conta LIKE '12 - %' THEN Valor ELSE 0 END) / MAX(\\\"População\\\"), 0) AS educacao\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "      AND ano = 2024\n",
        "      AND Coluna = 'Despesas Pagas'\n",
        "    GROUP BY UF\n",
        "    ORDER BY saude DESC\n",
        "\"\"\").df()\n",
        "\n",
        "x = range(len(per_capita))\n",
        "w = 0.4\n",
        "cores_s = ['#e74c3c' if uf == 'AL' else '#2980b9' for uf in per_capita['UF']]\n",
        "cores_e = ['#c0392b' if uf == 'AL' else '#27ae60' for uf in per_capita['UF']]\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(14, 6))\n",
        "ax.bar([i - w/2 for i in x], per_capita['saude'], width=w, color=cores_s, label='Saúde')\n",
        "ax.bar([i + w/2 for i in x], per_capita['educacao'], width=w, color=cores_e, label='Educação')\n",
        "ax.set_xticks(list(x))\n",
        "ax.set_xticklabels(per_capita['UF'], rotation=45)\n",
        "ax.set_ylabel('R$ por habitante')\n",
        "ax.set_title('Gasto Per Capita em Saúde e Educação (2024, Despesas Pagas)\\nDestaque em vermelho = Maceió')\n",
        "ax.legend()\n",
        "plt.tight_layout()\n",
        "plt.savefig('saidas/per_capita_saude_educacao.png', dpi=150)\n",
        "plt.show()\n",
        "\n",
        "maceio_s = per_capita.loc[per_capita['UF'] == 'AL', 'saude'].values[0]\n",
        "maceio_e = per_capita.loc[per_capita['UF'] == 'AL', 'educacao'].values[0]\n",
        "rank_s = per_capita['UF'].tolist().index('AL') + 1\n",
        "rank_e = per_capita.sort_values('educacao', ascending=False)['UF'].tolist().index('AL') + 1\n",
        "print(f'Maceió — Saúde: R$ {maceio_s:,.0f}/hab ({rank_s}º); Educação: R$ {maceio_e:,.0f}/hab ({rank_e}º)')"
    ]),

    md(["## 5. Evolução Temporal — Maceió vs Média das Capitais (2020–2024)\n",
        "\n",
        "Acompanhar a trajetória de Maceió ao longo dos anos, comparada à média geral,\n",
        "revela se o município está convergindo ou se distanciando das demais capitais."
    ]),

    code([
        "evolucao = con.execute(\"\"\"\n",
        "    SELECT\n",
        "        ano, UF,\n",
        "        ROUND(SUM(CASE WHEN Conta LIKE '10 - %' THEN Valor ELSE 0 END) / MAX(\\\"População\\\"), 0) AS saude_pc,\n",
        "        ROUND(SUM(CASE WHEN Conta LIKE '12 - %' THEN Valor ELSE 0 END) / MAX(\\\"População\\\"), 0) AS educ_pc\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "      AND ano <= 2024\n",
        "      AND Coluna = 'Despesas Pagas'\n",
        "    GROUP BY ano, UF\n",
        "    ORDER BY ano, UF\n",
        "\"\"\").df()\n",
        "\n",
        "media = evolucao.groupby('ano')[['saude_pc', 'educ_pc']].mean().reset_index()\n",
        "maceio = evolucao[evolucao['UF'] == 'AL'].copy()\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
        "\n",
        "axes[0].plot(media['ano'], media['saude_pc'], 'o--', color='steelblue', label='Média capitais')\n",
        "axes[0].plot(maceio['ano'], maceio['saude_pc'], 's-', color='#e74c3c', linewidth=2, label='Maceió')\n",
        "axes[0].set_title('Saúde — Per Capita (Pago)')\n",
        "axes[0].set_ylabel('R$ por habitante')\n",
        "axes[0].legend()\n",
        "\n",
        "axes[1].plot(media['ano'], media['educ_pc'], 'o--', color='steelblue', label='Média capitais')\n",
        "axes[1].plot(maceio['ano'], maceio['educ_pc'], 's-', color='#e74c3c', linewidth=2, label='Maceió')\n",
        "axes[1].set_title('Educação — Per Capita (Pago)')\n",
        "axes[1].set_ylabel('R$ por habitante')\n",
        "axes[1].legend()\n",
        "\n",
        "for ax in axes:\n",
        "    ax.set_xlabel('Ano')\n",
        "    ax.set_xticks([2020, 2021, 2022, 2023, 2024])\n",
        "\n",
        "plt.suptitle('Evolução do Gasto Per Capita — Maceió vs Média das Capitais', fontsize=13)\n",
        "plt.tight_layout()\n",
        "plt.savefig('saidas/evolucao_maceio.png', dpi=150)\n",
        "plt.show()"
    ]),

    md(["## 6. Síntese — Posicionamento de Maceió\n",
        "\n",
        "Resumo quantitativo de onde Maceió se posiciona em cada dimensão analisada."
    ]),

    code([
        "taxa_por_funcao = con.execute(\"\"\"\n",
        "    SELECT\n",
        "        UF,\n",
        "        SPLIT_PART(Conta, ' - ', 2) AS funcao,\n",
        "        ROUND(\n",
        "            100.0 * SUM(CASE WHEN Coluna = 'Despesas Pagas' THEN Valor ELSE 0 END) /\n",
        "            NULLIF(SUM(CASE WHEN Coluna = 'Despesas Empenhadas' THEN Valor ELSE 0 END), 0),\n",
        "        1) AS taxa\n",
        "    FROM finbra\n",
        "    WHERE tipo_conta = 'funcao'\n",
        "      AND ano BETWEEN 2020 AND 2024\n",
        "      AND Coluna IN ('Despesas Empenhadas', 'Despesas Pagas')\n",
        "    GROUP BY UF, Conta\n",
        "    ORDER BY funcao, taxa DESC\n",
        "\"\"\").df()\n",
        "\n",
        "ranking = (\n",
        "    taxa_por_funcao\n",
        "    .assign(rank=taxa_por_funcao.groupby('funcao')['taxa'].rank(ascending=False).astype(int))\n",
        "    .query(\"UF == 'AL'\")\n",
        "    .sort_values('taxa', ascending=False)\n",
        "    [['funcao', 'taxa', 'rank']]\n",
        "    .rename(columns={'funcao': 'Função', 'taxa': 'Taxa Exec. (%)', 'rank': 'Ranking (de 26)'})\n",
        ")\n",
        "\n",
        "print('Maceió — Taxa de Execução por Função (2020–2024):')\n",
        "print(ranking.to_string(index=False))\n",
        "\n",
        "print(f'\\nTaxa geral: {maceio_taxa}% — {maceio_rank}º entre 26 capitais')\n",
        "print(f'Saúde per capita 2024: R$ {maceio_s:,.0f}/hab — {rank_s}º lugar')\n",
        "print(f'Educação per capita 2024: R$ {maceio_e:,.0f}/hab — {rank_e}º lugar')"
    ]),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.13.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("passo4_analise.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Notebook gerado: passo4_analise.ipynb")
